### PR TITLE
fix patch `20_use_user-emacs-directory_at_startup.patch'

### PR DESCRIPTION
**Pull request by idcrook**
- update so patch applies to latest emacs source

### CODE REVIEW

**Comment by idcrook** [comment]
I was trying to use this to build emacs from source on macOS Mojave (Xcode 10 system).
I needed to update one of the patch files (included in this pull request).

I also encountered an issue where libxml2 header was missing from compilation of `xml.o` ("missing include <libxml/tree.h>").  I found a workaround but have not included it in the pull request.

I found a workaround by pointing explicitly to either one of homebrew libxml2 or Xcode SDK tools headers in the make step:

```diff
@@ -67,7 +67,7 @@ done
     --build=x86_64-apple-darwin \
     --without-dbus --with-ns
 
-make bootstrap -j8 || exit 1 && make install
+#CPPFLAGS="-I/usr/local/opt/libxml2/include/libxml2" make bootstrap -j4 || exit 1 && make install
+CPPFLAGS="-I$(xcrun --show-sdk-path)/usr/include/libxml2" make bootstrap -j4 || exit 1 && make install
```
Built on a dual-core MBP, not a quad-core, so also reduced the `-j8` to`-j4` for my system

With the updated patch and the explicit header file pointers, got a working Emacs.app with all the ImageMagick goodness)

**Comment by idcrook** [comment]
I also updated the Homebrew options on imagemagick build to following to update to non-deprecated flags and add `libheif`

```
brew install imagemagick \
--with-fontconfig \
--with-ghostscript \
--with-hdri \
--with-liblqr \
--with-librsvg \
--with-libwmf \
--with-little-cms \
--with-little-cms2 \
--with-openexr \
--with-perl \
--with-webp \
--with-libheif \
--with-openjpeg \
--with-fftw \
--with-pango \
--with-x11
```

with the last three specific for my system setup compared to the options listed in this projects README

```
--with-fftw \
--with-pango \
--with-x11
```

**Comment by renard** [comment]
Regarding the make threads can you check if you can automatically determine the cores using command:

```
sysctl -n hw.logicalcpu
```

You should get 4. I think this is more flexible and does not require change on build environment.

**Comment by idcrook** [comment]
> Regarding the make threads can you check if you can automatically determine the cores using command:
> 
> ```
> sysctl -n hw.logicalcpu
> ```
> You should get 4. I think this is more flexible and does not require change on build environment.

I didn't include the `CPPFLAGS=` or the `make -j##` in this patch/PR -- was just including here in comments for reference and reproducibility.

**Pull request closed without merging**
